"""The .vkp project file: a zip bundle that carries one whole project between machines.

Layout inside the bundle:
  vsk-project.json  format marker with the original conversation/session ids
  project.json      the full conversation document (state, references, versions, events, LLM context)
  assets/...        runtime/references/agent/{id}/  - user uploads and the clean pixels of every version
  generated/...     runtime/generated/{session}/    - public watermarked outputs the version urls point at

Import always mints a fresh conversation id (an import is a copy), rewrites the ids inside project.json - every
reference_key/url is path-coupled to those ids - and copies the files back under the new ids.
"""

import json
import uuid
import zipfile
from io import BytesIO
from pathlib import Path, PurePosixPath

from app.agent.store import Conversation, conversation_store
from app.core.config import get_settings
from app.core.paths import resolve_repo_path

FORMAT_NAME = "vsk-project"
FORMAT_VERSION = 1
MANIFEST_NAME = "vsk-project.json"
PROJECT_NAME = "project.json"
IMAGE_SUFFIXES = {".webp", ".png", ".jpg", ".jpeg"}
MAX_ENTRIES = 10_000
MAX_UNCOMPRESSED_BYTES = 1024 * 1024 * 1024
MAX_IMPORT_BYTES = 200 * 1024 * 1024


class ProjectFileError(ValueError):
    """The uploaded file is not a usable .vkp project."""


def _conversation_dir(conversation_id: str) -> Path:
    return resolve_repo_path(get_settings().reference_upload_dir) / "agent" / conversation_id


def _generated_dir(session_id: str) -> Path:
    return resolve_repo_path(get_settings().codex_output_dir) / session_id


def _collect_files(root: Path, arc_prefix: str, bundle: zipfile.ZipFile) -> None:
    if not root.is_dir():
        return
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES:
            bundle.write(path, arc_prefix + path.relative_to(root).as_posix())


def build_project_file(conversation: Conversation) -> bytes:
    """Bundle the conversation, its reference/version pixels and its public outputs into .vkp bytes."""
    buffer = BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as bundle:
        bundle.writestr(
            MANIFEST_NAME,
            json.dumps(
                {
                    "format": FORMAT_NAME,
                    "version": FORMAT_VERSION,
                    "conversation_id": conversation.id,
                    "session_id": conversation.state.character_session_id,
                    "exported_at": conversation.created_at,
                }
            ),
        )
        bundle.writestr(PROJECT_NAME, json.dumps(conversation.to_dict(), ensure_ascii=False))
        _collect_files(_conversation_dir(conversation.id), "assets/", bundle)
        # Versions generated by the fixture provider (tests / smoke runs) are served from the shared fixtures
        # directory and are not bundled; real backends write under runtime/generated and travel with the file.
        _collect_files(_generated_dir(conversation.state.character_session_id), "generated/", bundle)
    return buffer.getvalue()


def _check_entry_name(name: str) -> None:
    path = PurePosixPath(name)
    if (
        name.startswith("/")
        or "\\" in name
        or path.is_absolute()
        or any(part in ("..", "") for part in path.parts)
        or not (
            name in (MANIFEST_NAME, PROJECT_NAME) or name.startswith("assets/") or name.startswith("generated/")
        )
    ):
        raise ProjectFileError("unsafe_entry")


def import_project_file(data: bytes) -> Conversation:
    """Restore a .vkp bundle as a new conversation (a copy): never touches the project it was exported from."""
    try:
        archive = zipfile.ZipFile(BytesIO(data))
    except zipfile.BadZipFile as exc:
        raise ProjectFileError("not_a_zip") from exc
    names = archive.namelist()
    if len(names) > MAX_ENTRIES or sum(info.file_size for info in archive.infolist()) > MAX_UNCOMPRESSED_BYTES:
        raise ProjectFileError("project_too_large")
    for name in names:
        _check_entry_name(name)
    try:
        meta = json.loads(archive.read(MANIFEST_NAME))
        document = json.loads(archive.read(PROJECT_NAME))
    except KeyError as exc:
        raise ProjectFileError("missing_manifest") from exc
    except ValueError as exc:
        raise ProjectFileError("invalid_json") from exc
    if not isinstance(meta, dict) or meta.get("format") != FORMAT_NAME or not isinstance(document, dict):
        raise ProjectFileError("unknown_format")

    old_id = str(meta.get("conversation_id") or document.get("id") or "")
    old_session = str(meta.get("session_id") or document.get("state", {}).get("character_session_id") or "")
    new_id = str(uuid.uuid4())
    text = json.dumps(document, ensure_ascii=False)
    if old_id:
        text = text.replace(old_id, new_id)
    if old_session and old_session != old_id:
        text = text.replace(old_session, new_id)
    try:
        conversation = Conversation.from_dict(json.loads(text))
    except (KeyError, TypeError, ValueError) as exc:
        raise ProjectFileError("invalid_project") from exc
    conversation.id = new_id
    conversation.status = "idle"

    for name in names:
        if name in (MANIFEST_NAME, PROJECT_NAME):
            continue
        payload = archive.read(name)
        prefix = "assets/" if name.startswith("assets/") else "generated/"
        root = _conversation_dir(new_id) if prefix == "assets/" else _generated_dir(new_id)
        target = (root / PurePosixPath(name[len(prefix):])).resolve()
        try:
            target.relative_to(root.resolve())
        except ValueError as exc:  # defence in depth on top of _check_entry_name
            raise ProjectFileError("unsafe_entry") from exc
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload)

    conversation_store.save(conversation)
    return conversation


def project_file_download_name(conversation: Conversation) -> str:
    """ASCII-safe attachment name; the title is a nice-to-have, the id prefix is what makes it unique."""
    safe = "".join(char if char.isascii() and (char.isalnum() or char in "-_ ") else "-" for char in conversation.title)
    safe = "-".join(part for part in safe.split("-") if part) or "project"
    return f"{safe[:40]}-{conversation.id[:8]}.vkp"
